name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main, feature/** ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (Java ${{ matrix.java }})
    strategy:
      matrix:
        java: [ '8', '11' ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Check code format
        run: sbt scalafmtSbtCheck scalafmtCheckAll

      # Detect compile errors early
      - name: Compile
        run: sbt clean compile Test/compile

      - name: Test
        run: sbt test
